apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transaction
  template:
    metadata:
      labels:
        app: transaction
    spec:
      containers:
      - name: transaction
        image: nginx:alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
          requests:
            memory: 10Mi
            cpu: 10m
        ports:
        - containerPort: 80
